name: CI - Build

on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  NEXT_PUBLIC_BASE_URL: ${{ vars.NEXT_PUBLIC_BASE_URL }}

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 21.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true

      # Cache npm dependencies
      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-cache-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-cache-${{ matrix.node-version }}-

      - name: Install Dependencies
        run: |
          npm ci
          npm install -g @sanity/cli@latest

      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: .next/cache
          key: next-build-cache-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            next-build-cache-${{ matrix.node-version }}-

      - name: Build Next
        run: npm run build
